name: CMake

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt install -y pkg-config libgflags-dev libcurl4-openssl-dev libssl-dev libaio-dev libnl-3-dev libnl-genl-3-dev libglib2.0-dev
        sudo apt install -y uuid-dev libjson-c-dev libkmod-dev libsystemd-dev autoconf automake libtool libpci-dev nasm
        wget https://github.com/google/googletest/archive/refs/tags/release-1.10.0.tar.gz
        tar -zxvf release-1.10.0.tar.gz
        cd googletest-release-1.10.0/
        cmake CMakeLists.txt
        make
        sudo make install

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        git submodule update --init
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=1 -DENABLE_DSA=1 -DENABLE_ISAL=1 -DENABLE_QAT=1

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j8

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -j8 --output-on-failure -C $BUILD_TYPE
