name: DCO
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  #
  # Project checker
  #
  # based on https://github.com/containerd/project-checks/blob/main/action.yml
  project:
    name: DCO Checks
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/overlaybd
          fetch-depth: 100

      - name: set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      # TODO(fuweid): remove the env GO111MODULE=off in new version of go
      - name: install dependencies
        shell: bash
        env:
          GO111MODULE: off
        run: |
          echo "::group:: install dependencies"
          go get -u -v github.com/vbatts/git-validation
          go get -u -v github.com/kunalkushwaha/ltag
          echo "::endgroup::"

      - name: DCO checker
        shell: bash
        working-directory: src/github.com/containerd/overlaybd
        env:
          GITHUB_COMMIT_URL: ${{ github.event.pull_request.commits_url }}
          DCO_VERBOSITY: "-v"
          DCO_RANGE: ""
        run: |
          echo "::group:: DCO checks"
          set -eu -o pipefail
          if [ -z "${GITHUB_COMMIT_URL}" ]; then
          DCO_RANGE=$(jq -r '.after + "..HEAD"' ${GITHUB_EVENT_PATH})
          else
          DCO_RANGE=$(curl ${GITHUB_COMMIT_URL} | jq -r '.[0].parents[0].sha + "..HEAD"')
          fi

          range=
          [ ! -z "${DCO_RANGE}" ] && range="-range ${DCO_RANGE}"
          git-validation ${DCO_VERBOSITY} ${range} -run DCO
          echo "::endgroup::"
